auto merge logic change

diff --git a/.github/workflows/auto-merge.yml b/.github/workflows/auto-merge.yml
--- a/.github/workflows/auto-merge.yml
+++ b/.github/workflows/auto-merge.yml
@@ -12,53 +12,9 @@ permissions:
   pull-requests: write
 
 jobs:
-  status-check:
-    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Wait for status checks to complete
-        id: wait_for_status
-        run: |
-          # Define a variable
-          count=0
-
-          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
-          CHECK_NAME="ci/circleci: build"  # The name of the status check you are waiting for
-          SHA="${{ github.event.pull_request.head.sha }}"
-
-          echo "Waiting for status check '$CHECK_NAME' on commit $SHA"
-
-          # Loop until the status check passes or fails
-
-          while [ $count -lt 20 ]; do
-            echo "Count is $count"
-
-            # Increment the count
-            count=$((count + 1))
-
-            status=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-              "https://api.github.com/repos/${{ github.repository }}/commits/$SHA/status" | jq -r ".statuses[] | select(.context == \"$CHECK_NAME\") | .state")
-
-            echo "Current status: $status"
-
-            if [[ "$status" == "success" ]]; then
-              echo "Status check passed!"
-              break
-            elif [[ "$status" == "failure" ]]; then
-              echo "Status check failed!"
-              exit 1
-            else
-              echo "Status check still pending..."
-              sleep 100
-            fi
-          done
-
-
   auto-merge:
     if: contains(github.event.pull_request.labels.*.name, 'dependencies')
     runs-on: ubuntu-latest
-    needs: status-check
 
     steps:
       - name: Checkout repository
@@ -78,11 +34,6 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Auto-merge dependabot PR
-      #   if: contains(github.event.pull_request.labels.*.name, 'dependencies')
-      #   uses: pascalgn/automerge-action@v0.15.3
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Merge the PR if checks pass
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -91,21 +42,35 @@ jobs:
           OWNER="${{ github.repository_owner }}"
           REPO="${{ github.event.repository.name }}"
 
-          # # Check if all required status checks have passed
-          # STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-          #   "https://api.github.com/repos/${OWNER}/${REPO}/commits/${{ github.sha }}/status" \
-          #   | jq -r '.state')
+          # Define a variable
+          count=0
 
-          # if [ "$STATUS" = "success" ]; then
-            echo "All checks passed. Merging PR #${PR_NUMBER}"
+          while [ $count -lt 20 ]; do
+            echo "Count is $count"
 
-            # Merge the PR
-            curl -X PUT \
-              -H "Authorization: token $GITHUB_TOKEN" \
-              -H "Accept: application/vnd.github.v3+json" \
-              https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/merge \
-              -d '{"commit_title":"Auto merge PR after checks pass","merge_method":"merge"}'
-          # else
-            # echo "Checks did not pass. Current status: $STATUS"
-            # exit 1
-          # fi
+            # Increment the count
+            count=$((count + 1))
+
+            # Check if all required status checks have passed
+            STATUS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+              "https://api.github.com/repos/${OWNER}/${REPO}/commits/${{ github.sha }}/status" \
+              | jq -r '.state')
+
+            if [ "$STATUS" = "success" ]; then
+              echo "All checks passed. Merging PR #${PR_NUMBER}"
+
+              # Merge the PR
+              curl -X PUT \
+                -H "Authorization: token $GITHUB_TOKEN" \
+                -H "Accept: application/vnd.github.v3+json" \
+                https://api.github.com/repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/merge \
+                -d '{"commit_title":"Auto merge PR after checks pass","merge_method":"merge"}'
+            elif [[ "$STATUS" == "failure" ]]; then
+              echo "Status check failed!"
+              exit 1
+            else
+              echo "Status check still pending..."
+              sleep 10
+            fi
+          done
+
